# Generated by Django 2.1.5 on 2019-02-06 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_access', models.BooleanField(default=False, help_text='Is the user allowed to open the lock?')),
                ('lock', models.ForeignKey(help_text='Lock that the permissions act on', on_delete=django.db.models.deletion.CASCADE, to='lock_owners.Lock')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Username of user (max length: 100 characters)', max_length=100)),
                ('full_name', models.CharField(help_text='Full name of the user', max_length=200)),
                ('phone', models.CharField(help_text='User phone number (no spaces or dashes, 10 character max)', max_length=10)),
                ('email', models.EmailField(help_text='User email address', max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='permission',
            name='user',
            field=models.ForeignKey(help_text='User that permissions are for', on_delete=django.db.models.deletion.CASCADE, to='lock_owners.User'),
        ),
        migrations.AddField(
            model_name='owner',
            name='user',
            field=models.ForeignKey(help_text='User ID of the owner', on_delete=django.db.models.deletion.CASCADE, to='lock_owners.User'),
        ),
        migrations.AddField(
            model_name='lock',
            name='lock_owner',
            field=models.ForeignKey(help_text='Owner ID of the lock', on_delete=django.db.models.deletion.CASCADE, to='lock_owners.Owner'),
        ),
    ]
