# Generated by Django 2.1.7 on 2019-02-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock_owners', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='allowed_access',
            new_name='allowed_access_general',
        ),
        migrations.AddField(
            model_name='lock',
            name='address',
            field=models.CharField(default='N/A', help_text='Address of the home where the lock is', max_length=400),
        ),
        migrations.AddField(
            model_name='permission',
            name='time_end',
            field=models.TimeField(auto_now=True, help_text='Until what time can the user open the lock?'),
        ),
        migrations.AddField(
            model_name='permission',
            name='time_start',
            field=models.TimeField(auto_now=True, help_text='At what time can the user open the lock every day?'),
        ),
    ]
