# Generated by Django 2.1.7 on 2019-03-20 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lock_owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrangerReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(help_text='latitude of suspicious reporting')),
                ('longitude', models.FloatField(help_text='longitude of suspicious reporting')),
                ('stranger_report_time', models.DateTimeField(help_text='Date and time the report was made')),
                ('lock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lock_owners.Lock')),
            ],
        ),
    ]
