# Generated by Django 2.1.7 on 2019-04-21 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock_owners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strangerreport',
            name='stranger_report_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 21, 10, 52, 6, 827420), help_text='Date and time the report was made'),
        ),
        migrations.AlterField(
            model_name='tempauth',
            name='auth_code',
            field=models.CharField(default='1617826f-54fc-4738-9b06-af23c86cb1d0', editable=False, help_text='The temporary authentication code to assign to the user', max_length=200),
        ),
    ]
