# Generated by Django 2.1.7 on 2019-03-31 23:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lock_owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(default=datetime.datetime(2019, 3, 31, 23, 13, 46, 422199), help_text='Time that the temporary authentication code was assigned')),
                ('auth_code', models.CharField(default='15471a06-56ba-48f3-a57c-30108be59931', editable=False, help_text='The temporary authentication code to assign to the user', max_length=200)),
                ('lock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lock_owners.Lock')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lock_owners.Visitor')),
            ],
        ),
    ]
