# Generated by Django 2.1.7 on 2019-03-31 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock_owners', '0002_tempauth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempauth',
            name='auth_code',
            field=models.CharField(default='083f03ce-bcae-410e-9b8d-d2431b07ede8', editable=False, help_text='The temporary authentication code to assign to the user', max_length=200),
        ),
        migrations.AlterField(
            model_name='tempauth',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 31, 19, 14, 38, 230872), help_text='Time that the temporary authentication code was assigned'),
        ),
    ]
