# Generated by Django 2.1.7 on 2019-02-13 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lock_owners', '0002_auto_20190212_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lock',
            name='lock_owner',
            field=models.ForeignKey(help_text='User ID who owns the lock', on_delete=django.db.models.deletion.CASCADE, to='lock_owners.User'),
        ),
    ]
