# Generated by Django 2.1.7 on 2019-04-21 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock_owners', '0002_auto_20190421_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_bytes',
            field=models.BinaryField(blank=True, editable=True, help_text='Optional image data associated with this event', null=True),
        ),
        migrations.AlterField(
            model_name='strangerreport',
            name='stranger_report_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 21, 12, 39, 29, 712484), help_text='Date and time the report was made'),
        ),
        migrations.AlterField(
            model_name='tempauth',
            name='auth_code',
            field=models.CharField(default='dbd32df6-a6ae-491a-9268-465609c7e7d5', editable=False, help_text='The temporary authentication code to assign to the user', max_length=200),
        ),
        migrations.AlterField(
            model_name='tempauth',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 21, 12, 39, 29, 713008), help_text='Time that the temporary authentication code was assigned'),
        ),
    ]
