# Generated by Django 2.1.7 on 2019-04-22 02:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock_owners', '0003_auto_20190421_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='filename',
            field=models.CharField(blank=True, help_text='Optional filename associated with Image bytes. This is necessary if you are adding an image.', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='strangerreport',
            name='stranger_report_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 21, 22, 40, 4, 412668), help_text='Date and time the report was made'),
        ),
        migrations.AlterField(
            model_name='tempauth',
            name='auth_code',
            field=models.CharField(default='3c9c1e20-7b80-4744-997d-fd24cc70db51', editable=False, help_text='The temporary authentication code to assign to the user', max_length=200),
        ),
        migrations.AlterField(
            model_name='tempauth',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 21, 22, 40, 4, 413127), help_text='Time that the temporary authentication code was assigned'),
        ),
    ]
