# Generated by Django 2.1.7 on 2019-04-19 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock_owners', '0003_auto_20190331_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='lock',
            name='ip_address',
            field=models.CharField(default='127.0.0.1', help_text='IP Address of Raspberry Pi so we can connect to it.', max_length=14),
        ),
        migrations.AlterField(
            model_name='tempauth',
            name='auth_code',
            field=models.CharField(default='850fdeaa-c88a-41e3-a06c-2e18910f0c02', editable=False, help_text='The temporary authentication code to assign to the user', max_length=200),
        ),
        migrations.AlterField(
            model_name='tempauth',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 19, 19, 55, 45, 201227), help_text='Time that the temporary authentication code was assigned'),
        ),
    ]
