# Generated by Django 2.1.7 on 2019-03-24 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lock_owners', '0003_auto_20190324_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image of the user', upload_to='')),
                ('image_datetime', models.DateTimeField(help_text='Date and time the image was captured')),
                ('lock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lock_owners.Lock')),
                ('visitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lock_owners.Visitor')),
            ],
        ),
        migrations.RemoveField(
            model_name='userimage',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserImage',
        ),
    ]
