# Generated by Django 2.1.7 on 2019-04-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock_owners', '0003_auto_20190331_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempauth',
            name='auth_code',
            field=models.CharField(default='a4914212-6d5b-4adb-b21e-7975b4ae4e2d', editable=False, help_text='The temporary authentication code to assign to the user', max_length=200),
        ),
        migrations.AlterField(
            model_name='tempauth',
            name='time_created',
            field=models.DateTimeField(auto_now=True, help_text='Time that the temporary authentication code was assigned'),
        ),
    ]
