# Generated by Django 2.1.7 on 2019-04-22 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock_owners', '0004_auto_20190421_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strangerreport',
            name='stranger_report_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 22, 13, 51, 37, 809310), help_text='Date and time the report was made'),
        ),
        migrations.AlterField(
            model_name='tempauth',
            name='auth_code',
            field=models.CharField(default='d183bdb8-c8bd-49ce-b924-d11be2e97cac', editable=False, help_text='The temporary authentication code to assign to the user', max_length=200),
        ),
        migrations.AlterField(
            model_name='tempauth',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 22, 13, 51, 37, 809820), help_text='Time that the temporary authentication code was assigned'),
        ),
    ]
