# Generated by Django 2.1.7 on 2019-03-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock_owners', '0004_auto_20190324_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorimage',
            name='image',
            field=models.FileField(help_text='Image of the user', upload_to=''),
        ),
    ]
