# Generated by Django 2.1.7 on 2019-04-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock_owners', '0004_auto_20190403_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name of the resident', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='tempauth',
            name='auth_code',
            field=models.CharField(default='a90c4201-5a13-4467-a9ac-af7f58267447', editable=False, help_text='The temporary authentication code to assign to the user', max_length=200),
        ),
    ]
