# Generated by Django 2.1.7 on 2019-04-13 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lock_owners', '0005_auto_20190413_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='visitor',
            field=models.ForeignKey(help_text='User that permissions are for', on_delete=django.db.models.deletion.CASCADE, to='lock_owners.Resident'),
        ),
        migrations.AlterField(
            model_name='tempauth',
            name='auth_code',
            field=models.CharField(default='d6b0f565-0d55-4198-b6b3-530d3bc929ac', editable=False, help_text='The temporary authentication code to assign to the user', max_length=200),
        ),
    ]
