# Generated by Django 2.1.7 on 2019-02-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock_owners', '0006_auto_20190218_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='time_end',
            field=models.TimeField(help_text='Until what time can the user open the lock?'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='time_start',
            field=models.TimeField(help_text='At what time can the user open the lock every day?'),
        ),
    ]
