# Generated by Django 2.1.7 on 2019-03-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock_owners', '0006_auto_20190324_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorimage',
            name='filename',
            field=models.CharField(default='img.png', help_text='Name of the file to deliver the bytes as', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitorimage',
            name='image',
            field=models.BinaryField(editable=True, help_text='Image of the user, in bytes'),
        ),
    ]
