# Generated by Django 2.1.7 on 2019-04-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock_owners', '0006_auto_20190413_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='visitor',
            new_name='resident',
        ),
        migrations.AlterField(
            model_name='tempauth',
            name='auth_code',
            field=models.CharField(default='85a4749d-046e-4e6b-bc3e-0966c54f3911', editable=False, help_text='The temporary authentication code to assign to the user', max_length=200),
        ),
    ]
