# Generated by Django 2.1.7 on 2019-04-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock_owners', '0007_auto_20190413_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempauth',
            name='visitor',
        ),
        migrations.AlterField(
            model_name='tempauth',
            name='auth_code',
            field=models.CharField(default='d73bfc0a-1850-429a-b194-78dbe3dbc8eb', editable=False, help_text='The temporary authentication code to assign to the user', max_length=200),
        ),
    ]
