# Generated by Django 2.1.7 on 2019-04-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock_owners', '0008_auto_20190417_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempauth',
            name='auth_code',
            field=models.CharField(default='0c77ebfb-e473-487f-a6d4-8004907def6c', editable=False, help_text='The temporary authentication code to assign to the user', max_length=200),
        ),
    ]
