# Generated by Django 2.1.7 on 2019-04-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock_owners', '0009_auto_20190417_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempauth',
            name='visitor',
            field=models.CharField(default='Visitor Name', help_text='Identifying name for the visitor', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tempauth',
            name='auth_code',
            field=models.CharField(default='8e1184cf-707c-474d-81b4-2399cb783c69', editable=False, help_text='The temporary authentication code to assign to the user', max_length=200),
        ),
    ]
