# Generated by Django 2.1.7 on 2019-04-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock_owners', '0010_auto_20190417_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorimage',
            name='lock',
        ),
        migrations.RemoveField(
            model_name='visitorimage',
            name='visitor',
        ),
        migrations.AlterField(
            model_name='tempauth',
            name='auth_code',
            field=models.CharField(default='bde7c622-5780-44e4-96af-a828d64a4f4a', editable=False, help_text='The temporary authentication code to assign to the user', max_length=200),
        ),
        migrations.DeleteModel(
            name='VisitorImage',
        ),
    ]
