# Generated by Django 2.1.7 on 2019-04-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock_owners', '0011_auto_20190420_1428'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitor',
        ),
        migrations.AlterField(
            model_name='tempauth',
            name='auth_code',
            field=models.CharField(default='5a223cb0-35dd-4a69-9449-5f02d78c8386', editable=False, help_text='The temporary authentication code to assign to the user', max_length=200),
        ),
    ]
