# Generated by Django 2.1.7 on 2019-04-20 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lock_owners', '0012_auto_20190420_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_bytes', models.BinaryField(editable=True, help_text='Image in bytes')),
                ('resident', models.ForeignKey(help_text='Resident that this is an image of', on_delete=django.db.models.deletion.CASCADE, to='lock_owners.Resident')),
            ],
        ),
        migrations.AlterField(
            model_name='tempauth',
            name='auth_code',
            field=models.CharField(default='4f555c74-61c7-4813-a919-c6af73621bfb', editable=False, help_text='The temporary authentication code to assign to the user', max_length=200),
        ),
    ]
