# Generated by Django 2.1.7 on 2019-04-20 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lock_owners', '0013_auto_20190420_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='lock',
            field=models.ForeignKey(default=1, help_text='The lock that this Resident was created for', on_delete=django.db.models.deletion.CASCADE, to='lock_owners.Lock'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tempauth',
            name='auth_code',
            field=models.CharField(default='cebddaea-b18c-49e7-b6e9-3eb9a036e372', editable=False, help_text='The temporary authentication code to assign to the user', max_length=200),
        ),
    ]
