# Generated by Django 2.1.7 on 2019-04-20 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lock_owners', '0014_auto_20190420_1602'),
        ('lock_owners', '0004_auto_20190419_1955'),
    ]

    operations = [
    ]
