# Generated by Django 2.1.7 on 2019-04-20 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock_owners', '0015_merge_20190420_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, help_text='Time that the event happened'),
        ),
        migrations.AlterField(
            model_name='strangerreport',
            name='stranger_report_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 20, 17, 18, 52, 428865), help_text='Date and time the report was made'),
        ),
        migrations.AlterField(
            model_name='tempauth',
            name='auth_code',
            field=models.CharField(default='501ebf52-3339-4653-920e-a552f2b37ff5', editable=False, help_text='The temporary authentication code to assign to the user', max_length=200),
        ),
        migrations.AlterField(
            model_name='tempauth',
            name='time_created',
            field=models.DateTimeField(auto_now=True, help_text='Time that the temporary authentication code was assigned'),
        ),
    ]
